# Generated by Django 3.1.7 on 2021-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('entity_type', models.CharField(max_length=200)),
                ('individuals_affected', models.IntegerField(default=500)),
                ('breach_submission_date', models.DateTimeField()),
                ('breach_type', models.CharField(max_length=300)),
                ('location_of_breached_info', models.CharField(max_length=100)),
                ('business_associate_present', models.BooleanField(default=False)),
                ('web_description', models.CharField(max_length=1000)),
                ('under_investigation_now', models.BooleanField(default=False)),
            ],
        ),
    ]
