# Generated by Django 3.1.7 on 2021-03-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_breaches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breach',
            old_name='under_investigation_now',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='breach',
            old_name='entity_type',
            new_name='covered_entity_type',
        ),
        migrations.RenameField(
            model_name='breach',
            old_name='location_of_breached_info',
            new_name='location_of_breached_information',
        ),
        migrations.RenameField(
            model_name='breach',
            old_name='entity_name',
            new_name='name_of_covered_entity',
        ),
        migrations.RenameField(
            model_name='breach',
            old_name='breach_type',
            new_name='type_of_breach',
        ),
    ]
