# Generated by Django 3.1.7 on 2021-03-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_breaches', '0002_auto_20210307_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breach',
            name='breach_submission_date',
            field=models.DateField(),
        ),
    ]
