# Generated by Django 3.1.7 on 2021-03-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_breaches', '0003_auto_20210307_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breach',
            name='covered_entity_type',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='breach',
            name='location_of_breached_information',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='breach',
            name='name_of_covered_entity',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='breach',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breach',
            name='type_of_breach',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='breach',
            name='web_description',
            field=models.CharField(max_length=100000),
        ),
    ]
